R CMD INSTALL --build /tmp/packages/R6_2.5.1.tar.gz \
/tmp/packages/sys_3.4.tar.gz \
/tmp/packages/askpass_1.1.tar.gz \
/tmp/packages/brew_1.0-6.tar.gz \
/tmp/packages/brio_1.1.2.tar.gz \
/tmp/packages/rlang_0.4.11.tar.gz \
/tmp/packages/fastmap_1.1.0.tar.gz \
/tmp/packages/cachem_1.0.6.tar.gz \
/tmp/packages/ps_1.6.0.tar.gz \
/tmp/packages/processx_3.5.2.tar.gz \
/tmp/packages/callr_3.7.0.tar.gz \
/tmp/packages/clipr_0.7.1.tar.gz \
/tmp/packages/glue_1.4.2.tar.gz \
/tmp/packages/cli_3.0.1.tar.gz \
/tmp/packages/commonmark_1.7.tar.gz \
/tmp/packages/cpp11_0.3.1.tar.gz \
/tmp/packages/crayon_1.4.1.tar.gz \
/tmp/packages/openssl_1.4.5.tar.gz \
/tmp/packages/curl_4.3.2.tar.gz \
/tmp/packages/jsonlite_1.7.2.tar.gz \
/tmp/packages/credentials_1.3.1.tar.gz \
/tmp/packages/rprojroot_2.0.2.tar.gz \
/tmp/packages/desc_1.3.0.tar.gz \
/tmp/packages/diffobj_0.3.4.tar.gz \
/tmp/packages/digest_0.6.27.tar.gz \
/tmp/packages/ellipsis_0.3.2.tar.gz \
/tmp/packages/evaluate_0.14.tar.gz \
/tmp/packages/fansi_0.5.0.tar.gz \
/tmp/packages/fs_1.5.0.tar.gz \
/tmp/packages/rstudioapi_0.13.tar.gz \
/tmp/packages/zip_2.2.0.tar.gz \
/tmp/packages/gert_1.3.2.tar.gz \
/tmp/packages/xfun_0.25.tar.gz \
/tmp/packages/highr_0.9.tar.gz \
/tmp/packages/gitcreds_0.1.1.tar.gz \
/tmp/packages/mime_0.11.tar.gz \
/tmp/packages/httr_1.4.2.tar.gz \
/tmp/packages/ini_0.3.1.tar.gz \
/tmp/packages/gh_1.3.0.tar.gz \
/tmp/packages/markdown_1.1.tar.gz \
/tmp/packages/magrittr_2.0.1.tar.gz \
/tmp/packages/stringi_1.7.4.tar.gz \
/tmp/packages/stringr_1.4.0.tar.gz \
/tmp/packages/yaml_2.2.1.tar.gz \
/tmp/packages/knitr_1.33.tar.gz \
/tmp/packages/lifecycle_1.0.0.tar.gz \
/tmp/packages/memoise_2.0.0.tar.gz \
/tmp/packages/utf8_1.2.2.tar.gz \
/tmp/packages/vctrs_0.3.8.tar.gz \
/tmp/packages/pillar_1.6.2.tar.gz \
/tmp/packages/prettyunits_1.1.1.tar.gz \
/tmp/packages/withr_2.4.2.tar.gz \
/tmp/packages/pkgbuild_1.2.0.tar.gz \
/tmp/packages/pkgconfig_2.0.3.tar.gz \
/tmp/packages/pkgload_1.2.1.tar.gz \
/tmp/packages/praise_1.0.0.tar.gz \
/tmp/packages/purrr_0.3.4.tar.gz \
/tmp/packages/rappdirs_0.3.3.tar.gz \
/tmp/packages/sessioninfo_1.1.1.tar.gz \
/tmp/packages/xopen_1.0.0.tar.gz \
/tmp/packages/rcmdcheck_1.3.3.tar.gz \
/tmp/packages/tibble_3.1.4.tar.gz \
/tmp/packages/rematch2_2.1.2.tar.gz \
/tmp/packages/remotes_2.4.0.tar.gz \
/tmp/packages/xml2_1.3.2.tar.gz \
/tmp/packages/roxygen2_7.1.2.tar.gz \
/tmp/packages/rversions_2.1.1.tar.gz \
/tmp/packages/waldo_0.3.0.tar.gz \
/tmp/packages/testthat_3.0.4.tar.gz \
/tmp/packages/whisker_0.4.tar.gz \
/tmp/packages/usethis_2.0.1.tar.gz \
/tmp/packages/devtools_2.4.2.tar.gz 
 
