#! /bin/tcsh -f

# This the main GibbsCluster 2.0 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:  2.0e  2017, Apr 2
# Stand-alone version

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# Set FULL PATH to the GibbsCluster 2.0 directory (mandatory)
setenv	GIBBS /gibbscluster-2.0 

# set paths to Seq2Logo and/or R to generate graphics (optional)
set Seq2Logo = ""
set Rpath = "" 

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# main ========================================================================

set gibbs = $GIBBS/GibbsCluster-2.0e_SA.pl

if ( -x $gibbs ) then
    if ("$Seq2Logo" != "" && "$Rpath" != "") then
   	    $gibbs -H $Rpath -G $Seq2Logo $*
   	else
   		if ("$Seq2Logo" != "") then
   			 $gibbs -G $Seq2Logo $*
   		else if ("$Rpath" != "") then
   			 $gibbs -H $Rpath $*
   		else
   			$gibbs $*
   		endif
   	endif
else
   echo $gibbs not found
endif

# end of script ===============================================================
