 library(rCASC)
 source("scpopcorn.R")
 path=getwd()
 scratch=paste(path,"/scratch",sep="")
 dir.create(scratch)
 file1=paste(path,"/set1_interest.csv",sep="")
 file2=paste(path,"/setA_interest.csv",sep="")
 clustering.output1=paste(path,"/set1_interest_SAVER_clustering.output.csv",sep="")
 clustering.output2=paste(path,"/setA_interest_SAVER_clustering.output.csv",sep="")
 scpopCorn(group=c("sudo"), scratch.folder=scratch, file1=file1,file2=file2,separator=",",file3=clustering.output1,file4=clustering.output2,nCluster=20,seed=1111)
