R CMD INSTALL --build \
/tmp/packages/colorspace_2.0-2.tar.gz \
/tmp/packages/crayon_1.4.2.tar.gz \
/tmp/packages/utf8_1.2.2.tar.gz \
/tmp/packages/farver_2.1.0.tar.gz \
/tmp/packages/labeling_0.4.2.tar.gz \
/tmp/packages/R6_2.5.1.tar.gz \
/tmp/packages/RColorBrewer_1.1-2.tar.gz \
/tmp/packages/viridisLite_0.4.0.tar.gz \
/tmp/packages/fansi_0.5.0.tar.gz \
/tmp/packages/magrittr_2.0.1.tar.gz \
/tmp/packages/pkgconfig_2.0.3.tar.gz \
/tmp/packages/digest_0.6.28.tar.gz \
/tmp/packages/glue_1.5.0.tar.gz \
/tmp/packages/gtable_0.3.0.tar.gz \
/tmp/packages/isoband_0.2.5.tar.gz \
/tmp/packages/rlang_0.4.12.tar.gz \
/tmp/packages/withr_2.4.2.tar.gz \
/tmp/packages/cli_3.1.0.tar.gz \
/tmp/packages/lifecycle_1.0.1.tar.gz \
/tmp/packages/munsell_0.5.0.tar.gz \
/tmp/packages/ellipsis_0.3.2.tar.gz \
/tmp/packages/vctrs_0.3.8.tar.gz \
/tmp/packages/scales_1.1.1.tar.gz \
/tmp/packages/pillar_1.6.4.tar.gz \
/tmp/packages/tibble_3.1.6.tar.gz \
/tmp/packages/ggplot2_3.3.5.tar.gz \
/tmp/packages/argparser_0.7.1.tar.gz \
